<?php

namespace TomatoPHP\FilamentMeta\Tests\Resources;

use Filament\Resources\Resource;
use Filament\Schemas\Schema;
use Filament\Tables\Table;
use TomatoPHP\FilamentMeta\Filament\RelationManager\MetaRelationManager;
use TomatoPHP\FilamentMeta\Tests\Models\User;
use TomatoPHP\FilamentMeta\Tests\Resources\UserResource\Pages;

class UserResource extends Resource
{
    protected static ?int $navigationSort = 9;

    protected static string | null | \BackedEnum $navigationIcon = 'heroicon-o-user';

    public static function getModel(): string
    {
        return User::class;
    }

    public static function form(Schema $form): Schema
    {
        return $form; // TODO: Change the autogenerated stub
    }

    public static function table(Table $table): Table
    {
        return $table; // TODO: Change the autogenerated stub
    }

    public static function getRelations(): array
    {
        return [
            MetaRelationManager::class,
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ManageUsers::route('/'),
            'edit' => Pages\EditUser::route('/{record}/edit'),
        ];
    }
}
